spring.application.name=SPS
#Spring
spring.datasource.url=jdbc:mysql://localhost/ssos
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.thymeleaf.template-resolver-order=0
#security.basic.enabled=false
#management.security.enabled=false
#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=blue247114@gmail.com
spring.mail.password=ukksjmwugvltcidc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties..mail.smtp.starttls.enable=true
#facebook
spring.security.oauth2.client.registration.facebook.client-id=588969167292372
spring.security.oauth2.client.registration.facebook.client-secret=7aa8c6f507acb13ff0a26f8d13e95d1d
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri=http://localhost:8080/signin-facebook
